2017-12-12 09:52:14 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] >>>>>>>>>>>>>查找商品，找不到该商品：16C0121
 2017-12-12 09:59:11 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] No operations allowed after connection closed.
 2017-12-12 09:59:11 [com.mchange.v2.c3p0.impl.NewPooledConnection]-[WARN] [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
 2017-12-12 09:59:11 [com.mchange.v2.c3p0.impl.NewPooledConnection]-[WARN] [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state. ] which will not be reported to listeners!
 com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:888)
	at com.mysql.jdbc.Connection.getMutex(Connection.java:3755)
	at com.mysql.jdbc.Connection.rollback(Connection.java:5251)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:860)
	at com.heso.service.order.consume.ConsumeOrder.genarate2(ConsumeOrder.java:466)
	at com.heso.service.order.consume.ConsumeOrder.innerOrder(ConsumeOrder.java:1245)
	at com.heso.transaction.outer.Transaction_001080.execute(Transaction_001080.java:227)
	at com.heso.data.TransDataProcess.execute(TransDataProcess.java:101)
	at com.heso.transaction.outer.Transaction_001080.main(Transaction_001080.java:378)
2017-12-12 09:59:23 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 2017-12-12 10:05:53 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 101300
 2017-12-12 10:27:41 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] No operations allowed after connection closed.
 2017-12-12 10:27:41 [com.mchange.v2.c3p0.impl.NewPooledConnection]-[WARN] [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
 2017-12-12 10:27:41 [com.mchange.v2.c3p0.impl.NewPooledConnection]-[WARN] [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state. ] which will not be reported to listeners!
 com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:888)
	at com.mysql.jdbc.Connection.getMutex(Connection.java:3755)
	at com.mysql.jdbc.Connection.rollback(Connection.java:5251)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:860)
	at com.heso.service.order.consume.ConsumeOrder.genarate2(ConsumeOrder.java:466)
	at com.heso.service.order.consume.ConsumeOrder.innerOrder(ConsumeOrder.java:1245)
	at com.heso.transaction.outer.Transaction_001080.execute(Transaction_001080.java:227)
	at com.heso.data.TransDataProcess.execute(TransDataProcess.java:101)
	at com.heso.transaction.outer.Transaction_001080.main(Transaction_001080.java:378)
2017-12-12 10:34:42 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 2017-12-12 10:43:36 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] No operations allowed after connection closed.
 2017-12-12 10:43:36 [com.mchange.v2.c3p0.impl.NewPooledConnection]-[WARN] [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
 2017-12-12 10:43:36 [com.mchange.v2.c3p0.impl.NewPooledConnection]-[WARN] [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state. ] which will not be reported to listeners!
 com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:888)
	at com.mysql.jdbc.Connection.getMutex(Connection.java:3755)
	at com.mysql.jdbc.Connection.rollback(Connection.java:5251)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:860)
	at com.heso.service.order.consume.ConsumeOrder.genarate2(ConsumeOrder.java:466)
	at com.heso.service.order.consume.ConsumeOrder.innerOrder(ConsumeOrder.java:1245)
	at com.heso.transaction.outer.Transaction_001080.execute(Transaction_001080.java:227)
	at com.heso.data.TransDataProcess.execute(TransDataProcess.java:101)
	at com.heso.transaction.outer.Transaction_001080.main(Transaction_001080.java:378)
2017-12-12 10:43:37 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 2017-12-12 11:05:02 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] No operations allowed after connection closed.
 2017-12-12 11:05:05 [com.mchange.v2.c3p0.impl.NewPooledConnection]-[WARN] [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
 2017-12-12 11:05:05 [com.mchange.v2.c3p0.impl.NewPooledConnection]-[WARN] [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state. ] which will not be reported to listeners!
 com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:888)
	at com.mysql.jdbc.Connection.getMutex(Connection.java:3755)
	at com.mysql.jdbc.Connection.rollback(Connection.java:5251)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:860)
	at com.heso.service.order.consume.ConsumeOrder.genarate2(ConsumeOrder.java:463)
	at com.heso.service.order.consume.ConsumeOrder.innerOrder(ConsumeOrder.java:1242)
	at com.heso.transaction.outer.Transaction_001080.execute(Transaction_001080.java:227)
	at com.heso.data.TransDataProcess.execute(TransDataProcess.java:101)
	at com.heso.transaction.outer.Transaction_001080.main(Transaction_001080.java:378)
2017-12-12 11:05:11 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 2017-12-12 13:11:59 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 101300
 2017-12-12 13:15:02 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 100300
 2017-12-12 15:09:57 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 000150
 2017-12-12 15:09:57 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 2017-12-12 15:18:30 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 000150
 2017-12-12 15:18:30 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 2017-12-12 18:37:14 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 000150
 2017-12-12 18:37:14 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 2017-12-12 18:40:35 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 000150
 2017-12-12 18:40:35 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 2017-12-12 18:57:58 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 000150
 2017-12-12 18:58:17 [com.heso.service.order.consume.ConsumeOrder]-[ERROR] 
 